pull_request_rules:
  - name: Automatic merge on review
    # https://doc.mergify.io/examples.html#require-all-requested-reviews-to-be-approved 
    conditions:
      - "#approved-reviews-by>=3"
      - "#changes-requested-reviews-by=0"
      - base=master
      - label=approval + 2
    actions:
      merge:
        method: merge
      delete_head_branch: {}